### ISSUE TITLE
Create UrlMappings file with proper file name.

### ISSUE THREAD

**Issue by rpalcolea** [grails-profiles/plugin#2]
This is an enhancement ticket. 
## Context

https://github.com/grails/grails-core/issues/9657 
https://grails.slack.com/archives/plugins/p1471423052000063

People has issues with the naming convention for the `UrlMappings` file in plugins.
## Proposal

Prepend the plugin name to the UrlMappings filename to prevent unpredictable results.
## Solution

I was thinking on adding the following to the `profile.yml`

``` yml
excludes:
  - grails-app/controllers/UrlMappings.groovy
```

I would like to know if this excludes the default UrlMappings created during `grails create-plugin`

After that, create the `UrlMappings` artifact as follows:

`@grails.codegen.projectClassName@UrlMappings.groovy`

``` groovy
package @grails.codegen.defaultPackage@

class @grails.codegen.projectClassName@UrlMappings {

    static mappings = {
        "/$controller/$action?/$id?(.$format)?"{
            constraints {
                // apply constraints here
            }
        }

        "/"(view:"/index")
        "500"(view:'/error')
        "404"(view:'/notFound')
    }
}
```

Is this something that could generate value for this profile or is it a `web-plugin` profile specific issue.

Probably I need to understand more about the profiles but I think this could be a good addition to the existing profile. I would like to know how the `UrlMappings.groovy` is created in a `plugin`. I couldn't find the artifact in the `plugin` and `web-plugin` profiles but I did find it in the `web` profile.

What do you think?

Thanks

Roberto

**Comment by jameskleeh** [comment]
When you do `create-plugin`, the default profile is `web-plugin` which has a dependency on `plugin` and `web`. The `UrlMappings.groovy` file is coming from the `web` profile.

Where are you seeing `excludes` as a supported option in a `profile.yml`?

**Comment by rpalcolea** [comment]
Got it... could be helpful implementing the logic that I mentioned before but in the `web-plugin`? I don't know if this is something that you want.

**Comment by jameskleeh** [comment]
The proper place to do it would be in the web-plugin. Whether or not it should be done I'm not sure

**Comment by rpalcolea** [comment]
Ok, well I'll open the issue there and see how it goes. thanks!
